# Python NumPy Library

In [1]:
import numpy as np 

In [12]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print("\n")
print("Array 1 ",a)
print("Array 2 ",b)
print("\n")
print(f"Addition of{a} and {b} is ",a+b)



Array 1  [1 2 3]
Array 2  [4 5 6]


Addition of[1 2 3] and [4 5 6] is  [5 7 9]


# NumPy N-Dimentional Array Creation 

In [20]:
n_dimention = np.array([[11,22,33],[44,55,66],[77,88,99]])
print("3 Dimentional Array 3 rows and 3 columns \n\n",n_dimention)

3 Dimentional Array 3 rows and 3 columns 

 [[11 22 33]
 [44 55 66]
 [77 88 99]]


# Slicing In NumPy 

In [208]:
slicing = np.array([11,22,33,44,55])

print(f"Original Array is {slicing} \n")

print("slicing[0:3]:- ",slicing[0:3])
print("slicing[2:] :- ",slicing[2:])
print("slicing[:4] :- ",slicing[:4])
print("slicing[:]  :- ",slicing[:])

n_Dimen_Array = np.array([[1,2,3,4],[5,6,7,8]])
print(f"\n\nN- Dimentional Array in NumPy {n_Dimen_Array} \n\n")

print(n_Dimen_Array[0:2,0:2]," :- N_Dimention_Array [0:2,0:2] \n")
print(n_Dimen_Array[0,0:2],"   :- In Index 0 N_Dimention_Array [0,0:2] \n")
print(n_Dimen_Array[1,0:2],"   :- In Index 1 N_Dimention_Array [1,0:2] \n")
print(n_Dimen_Array[1,2],"       :- In Index 1 N_Dimention_Array [1,2] ")


Original Array is [11 22 33 44 55] 

slicing[0:3]:-  [11 22 33]
slicing[2:] :-  [33 44 55]
slicing[:4] :-  [11 22 33 44]
slicing[:]  :-  [11 22 33 44 55]


N- Dimentional Array in NumPy [[1 2 3 4]
 [5 6 7 8]] 


[[1 2]
 [5 6]]  :- N_Dimention_Array [0:2,0:2] 

[1 2]    :- In Index 0 N_Dimention_Array [0,0:2] 

[5 6]    :- In Index 1 N_Dimention_Array [1,0:2] 

7        :- In Index 1 N_Dimention_Array [1,2] 


# Attribute of Array

In [59]:
print("Shape of Array is  :- ",np.shape(n_Dimen_Array))
print("Size of Array is   :- ",np.size(n_Dimen_Array))
print("Dimention of Array :- ",np.ndim(n_Dimen_Array))
print("Dimention of Array :- ",n_Dimen_Array.dtype)

Shape of Array is  :-  (2, 4)
Size of Array is   :-  8
Dimention of Array :-  2
Dimention of Array :-  int64


# Inspecting an Array 

In [80]:
a =[[12,13,14],[15,16,17]]
arr = np.array(a)

print("Type of Array   :- ",arr.dtype)
print("Size of Array   :- ",np.size(arr))
print("No of rows and Columns of Array   :- ",arr.shape)
print("Length of Array :- ",len(arr))
print("Type of array   :-",type(arr) )
print(f"Typecasting of Array In Interger \n\n {arr} \n\n After Typecasting :- \n\n",arr.astype(float))


Type of Array   :-  int64
Size of Array   :-  6
No of rows and Columns of Array   :-  (2, 3)
Length of Array :-  2
Type of array   :- <class 'numpy.ndarray'>
Typecasting of Array In Interger 

 [[12 13 14]
 [15 16 17]] 

 after Typecasting :- 

 [[12. 13. 14.]
 [15. 16. 17.]]


# Mathamatical Operation 

In [102]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])

print("\n\nAddition of Two Array \n")
print("Without Function \n",arr1+arr2)
print("With Function \n",np.add(arr1,arr2))

print("\n\n Substraction of Two Array \n")
print("Without Function \n",arr1-arr2)
print("With Function \n",np.subtract(arr1,arr2))

print("\n\nMultipllication of Two Array \n")
print("Without Function \n",arr1*arr2)
print("With Function \n",np.multiply(arr1,arr2))

print("\n\nDivision of Two Array \n")
print("Without Function \n",arr1/arr2)
print("With Function \n",np.divide(arr1,arr2))

print("\n\n Power Function")
print(np.power(arr1,2))

print("\n\n Square Root Function ")
arr2 = np.array([16 ,25,36])
print(np.sqrt(arr2))



Addition of Two Array 

Without Function 
 [[ 8 10 12]
 [14 16 18]]
With Function 
 [[ 8 10 12]
 [14 16 18]]


 Substraction of Two Array 

Without Function 
 [[-6 -6 -6]
 [-6 -6 -6]]
With Function 
 [[-6 -6 -6]
 [-6 -6 -6]]


Multipllication of Two Array 

Without Function 
 [[ 7 16 27]
 [40 55 72]]
With Function 
 [[ 7 16 27]
 [40 55 72]]


Division of Two Array 

Without Function 
 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]
With Function 
 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


 Power Function
[[ 1  4  9]
 [16 25 36]]


 Square Root Function 
[4. 5. 6.]


# Join and Split the Array 

In [134]:
arr3 = np.array([1,2,3])
arr4 = np.array([4,5,6])

print(f"\nConcatenate the {arr3} and {arr4}  :- ",np.concatenate([arr3,arr4]))

arr5 = np.array([[1,2],[6,3]])
arr6 = np.array([[4,5],[9,6]])

print("\nAxis 0 for Horizontal Concatenate :- \n\n",np.concatenate([arr5,arr6], axis = 0))

print("\nAxis 1 for Vertical Concatenate :- \n\n",np.concatenate([arr5,arr6], axis = 1))

print("\n\n Vertical Concatenate using Function :- \n\n",np.vstack([arr5,arr6]))

print("\n\n Horizontal Concatenate using Function :- \n\n",np.hstack([arr5,arr6]))

print("\n\n Split The array\n\n")

array =np.array([1,2,3,4,5,6,7,8,9,10])

split_array = np.array_split(array,3)

print(f"Befor Spliting array \n\n{array} \n\nAfter Sliting \n\n{split_array}\n\n")



Concatenate the [1 2 3] and [4 5 6]  :-  [1 2 3 4 5 6]

Axis 0 for Horizontal Concatenate :- 

 [[1 2]
 [6 3]
 [4 5]
 [9 6]]

Axis 1 for Vertical Concatenate :- 

 [[1 2 4 5]
 [6 3 9 6]]


 Vertical Concatenate using Function :- 

 [[1 2]
 [6 3]
 [4 5]
 [9 6]]


 Horizontal Concatenate using Function :- 

 [[1 2 4 5]
 [6 3 9 6]]


 Split The array


Befor Spliting array 

[ 1  2  3  4  5  6  7  8  9 10] 

After Sliting 

[array([1, 2, 3, 4]), array([5, 6, 7]), array([ 8,  9, 10])]




# Add And Remove Element from Array

In [162]:
arr = np.array([[1,2,],[3,4]])
print(f"Original Array \n{arr} \nAfter Appending\n",np.append(arr,[5,6,7]))
print(f"\nOriginal Array \n{arr} \nAfter Inserting\n",np.insert(arr,1,[5,6,7]))
print(f"\nOriginal Array \n{arr} \nAfter Deleting\n",np.delete(arr,1,axis =1))



Original Array 
[[1 2]
 [3 4]] 
After Appending
 [1 2 3 4 5 6 7]

Original Array 
[[1 2]
 [3 4]] 
After Inserting
 [1 5 6 7 2 3 4]

Original Array 
[[1 2]
 [3 4]] 
After Deleting
 [[1]
 [3]]


# Search,Sort and Filter 

In [182]:
ar = np.array([7,8,3,4,1,2])
print(f"Befor sorting \n\n {ar} \n\nAfter sorting\n\n",np.sort(ar))

ab = np.where(ar==2)
print("\n\nIndex of 2 is  :- ",ab)

abc = np.where(ar % 2 == 0)
print("\n\nEven Value are :- ",ar[abc])

sorted_array = np.sort(ar)

print("\nIndex of 4 is  :-",np.searchsorted(sorted_array,4))

ex = sorted_array > 2

ex1 = sorted_array[ex]
print("\n\nFilter Array ",ex1)

Befor sorting 

 [7 8 3 4 1 2] 

After sorting

 [1 2 3 4 7 8]


Index of 2 is  :-  (array([5]),)


Even Value are :-  [8 4 2]

Index of 4 is  :- 3


Filter Array  [3 4 7 8]


# Agregating Functions in NumPy

In [196]:
ar1 = np.array([7,8,3,4,1,2])

print(f"\nMaximum Value from {ar1} are :- ",np.max(ar1))
print(f"\nMinimum Value from {ar1} are :- ",np.min(ar1))
print(f"\nSum of Value from {ar1} are :- ",np.sum(ar1))
print(f"\nSize of {ar1} are :- ",np.size(ar1))
print(f"\nMean of {ar1} are :- ",np.mean(ar1))
print(f"\nCumulative Sum from {ar1} are :- ",np.cumsum(ar1))
print(f"\nCumulative Product from {ar1} are :- ",np.cumprod(ar1))


price = np.array([100,150,199,200,250,130])
quantity = np.array([10,50,30,40,30,10])

print(f"\n\nPirce of Product is {price}")
print(f"\nQunatity of Product is {quantity}")

cumulative_product = np.cumprod([price,quantity],axis = 0)
print("\nTotal Revenue :- ",cumulative_product[1].sum())




Maximum Value from [7 8 3 4 1 2] are :-  8

Minimum Value from [7 8 3 4 1 2] are :-  1

Sum of Value from [7 8 3 4 1 2] are :-  25

Size of [7 8 3 4 1 2] are :-  6

Mean of [7 8 3 4 1 2] are :-  4.166666666666667

Cumulative Sum from [7 8 3 4 1 2] are :-  [ 7 15 18 22 23 25]

Cumulative Product from [7 8 3 4 1 2] are :-  [   7   56  168  672  672 1344]


Pirce of Product is [100 150 199 200 250 130]

Qunatity of Product is [10 50 30 40 30 10]

Total Revenue :-  31270


# Statistical Function

In [207]:
import statistics as stats

baked_food =np.array([2,3,5,7,8,5,3])

print("Mean of Value    :-",np.mean(baked_food))
print("Median of Value  :-",np.median(baked_food))
print("Mode of Value    :-",stats.mode(baked_food))
print("Standared Deviation of Value :-",np.std(baked_food))
print("Varience of Value:- ",np.var(baked_food))

tobaco_consumption = [30,50,10,30,50,40]
deaths = [100,120,70,100,120,112]

print("\nCorrealtion Coefficient :-\n\n",np.corrcoef([tobaco_consumption,deaths]))

print("\n-1 Represent inversely Propostional Relationship \n 1 Represent Propostional Relationship \n 0 Means No Relationship")


Mean of Value    :- 4.714285714285714
Median of Value  :- 5.0
Mode of Value    :- 3
Standared Deviation of Value :- 2.0503857277724746
Varience of Value:-  4.204081632653061

Correaltion Coefficient :-

 [[1.         0.99015454]
 [0.99015454 1.        ]]

-1 Represent inversely Propostional Relationship 
 1 Represent Propostional Relationship 
 0 Means No Relationship
